package ShantanuBhadoria::Site::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'ShantanuBhadoria::Schema',
    
    connect_info => {
        dsn               => ShantanuBhadoria::Config->get('db')->{dsn}, 
        user              => ShantanuBhadoria::Config->get('db')->{user}, 
        password          => ShantanuBhadoria::Config->get('db')->{password},
    }
);

=head1 NAME

ShantanuBhadoria::Site::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<ShantanuBhadoria::Site>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ShantanuBhadoria::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.49

=head1 AUTHOR

Shantanu Bhadoria

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
