package ShantanuBhadoria::Site::Model::Schema;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'ShantanuBhadoria::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:SB:localhost:3306',
        user => 'root',
        password => 'secret',
    }
);

=head1 NAME

ShantanuBhadoria::Site::Model::Schema - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<ShantanuBhadoria::Site>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ShantanuBhadoria::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.58

=head1 AUTHOR

Shan

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
